### ISSUE TITLE
Render panics with enough concurrent  requests incoming

### ISSUE THREAD

**Issue by flexd** [unrolled/render#15]
I might be doing something wrong here, but I end up getting this fine error attempting to load-test my application (or just refreshing a lot).

Which template that is redefined constantly changes, so it is not the problem.
Have you encountered this before?

```go
2015/01/06 15:03:25 Recovering from Panic: template: redefinition of template "partials/transaction_rows"
goroutine 2785 [running]:
github.com/unrolled/recovery.func·001()
        /home/kristoffer/code/go/src/github.com/unrolled/recovery/recovery.go:86 +0x12a
html/template.Must(0x0, 0x7f89c3f72b00, 0xc20800b600, 0x0)
        /usr/local/go/src/html/template/template.go:304 +0x50
github.com/unrolled/render.func·003(0xc208122ed0, 0x28, 0x7f89c3f770f0, 0xc208177b30, 0x0, 0x0, 0x0, 0x0) 
        /home/kristoffer/code/go/src/github.com/unrolled/render/render.go:167 +0x539
path/filepath.walk(0xc208122ed0, 0x28, 0x7f89c3f770f0, 0xc208177b30, 0xc20819f740, 0x0, 0x0) 
        /usr/local/go/src/path/filepath/path.go:347 +0x91
path/filepath.walk(0xc208178580, 0x12, 0x7f89c3f770f0, 0xc2081760a0, 0xc20819f740, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:372 +0x51d
path/filepath.walk(0x8c2e50, 0x9, 0x7f89c3f770f0, 0xc20811c230, 0xc20819f740, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:372 +0x51d
path/filepath.Walk(0x8c2e50, 0x9, 0xc20819f740, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:394 +0xf2
github.com/unrolled/render.(*Render).compileTemplates(0xc20808c000)
        /home/kristoffer/code/go/src/github.com/unrolled/render/render.go:173 +0x106 
github.com/unrolled/render.(*Render).HTML(0xc20808c000, 0x7f89c3f78dc0, 0xc20801ea00, 0xc8, 0x892ef0, 0x5, 0x0, 0x0, 0x0, 0x0, ...) 
        /home/kristoffer/code/go/src/github.com/unrolled/render/render.go:250 +0x3f 
github.com/flexd/evego/views.(*RequestHandler).Welcome(0xc2080e1880, 0x7f89c3f78dc0, 0xc20801ea00, 0xc2080324e0) 
        /home/kristoffer/code/go/src/github.com/flexd/evego/views/index.go:8 +0xc0 
github.com/flexd/evego/views.*RequestHandler.Welcome·fm(0x7f89c3f78dc0, 0xc20801ea00, 0xc2080324e0) 
        /home/kristoffer/code/go/src/github.com/flexd/evego/main.go:72 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2080da680, 0x7f89c3f78dc0, 0xc20801ea00, 0xc2080324e0)
        /usr/local/go/src/net/http/server.go:1265 +0x41 
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080e2fa0, 0x7f89c3f78dc0, 0xc20801ea00, 0xc2080324e0) 
        /home/kristoffer/code/go/src/github.com/gorilla/mux/mux.go:98 +0x297
github.com/unrolled/recovery.func·002(0x7f89c3f78dc0, 0xc20801ea00, 0xc2080324e0)
        /home/kristoffer/code/go/src/github.com/unrolled/recovery/recovery.go:92 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc20801f040, 0x7f89c3f78dc0, 0xc20801ea00, 0xc2080324e0)
        /usr/local/go/src/net/http/server.go:1265 +0x41 
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x7f89c3f78a78, 0xc20801f080, 0x7f89c3f78988, 0xc20801f040, 0x7f89c3f78d18, 0xc208164000, 0xc2080324e0) 
        /home/kristoffer/code/go/src/github.com/gorilla/handlers/handlers.go:75 +0x1be 
github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc20801f0a0, 0x7f89c3f78d18, 0xc208164000, 0xc2080324e0) 
        <autogenerated>:14 +0xbe
github.com/gorilla/context.func·001(0x7f89c3f78d18, 0xc208164000, 0xc2080324e0)
        /home/kristoffer/code/go/src/github.com/gorilla/context/context.go:141 +0x80
net/http.HandlerFunc.ServeHTTP(0xc2080db680, 0x7f89c3f78d18, 0xc208164000, 0xc2080324e0)
        /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2080314a0, 0x7f89c3f78d18, 0xc208164000, 0xc2080324e0)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208164500)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by flexd** [comment]
This might actually be me being an idiot, keep tuned :+1:

**Comment by flexd** [comment]
Actually it turns out that while IsDevelopment is true, `render` will break like this once it has enough traffic. This makes complete sense of course, but I did not think of that when it happened!

**Comment by unrolled** [comment]
Ahhh, thats good to know! I'll make myself a todo item and add a blurb in the documentation about this.
