### ISSUE TITLE
Rendering the wrong HTML template under load

### ISSUE THREAD

**Issue by 7fffffff** [unrolled/render#57]
Try running https://github.com/7fffffff/unrolledrendertest while also running an at least 2 instances of a http benchmark program (I used [wrk](https://github.com/wg/wrk) for this)

```unrolledrendertest```
```wrk -t 4 -c 4 -d 30s http://localhost:8080/example1```
```wrk -t 4 -c 4 -d 30s http://localhost:8080/example2```

which leads to

```
2016/12/19 19:41:11 http: panic serving 127.0.0.1:46640: expected example2, got example1
goroutine 1530 [running]:
net/http.(*conn).serve.func1(0xc4204d5e80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x6fe120, 0xc4200ca390)
	/usr/local/go/src/runtime/panic.go:458 +0x243
main.main.func2(0x8cf560, 0xc4200744e0, 0xc42022cd20)
	/home/u/go/src/github.com/7fffffff/unrolledrendertest/main.go:27 +0x3bd
net/http.HandlerFunc.ServeHTTP(0xc42000d300, 0x8cf560, 0xc4200744e0, 0xc42022cd20)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0x8efe20, 0x8cf560, 0xc4200744e0, 0xc42022cd20)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420108380, 0x8cf560, 0xc4200744e0, 0xc42022cd20)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4204d5e80, 0x8cfba0, 0xc420014280)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
2016/12/19 19:41:11 http: panic serving 127.0.0.1:46646: expected example1, got example2
goroutine 1514 [running]:
net/http.(*conn).serve.func1(0xc4200ba100)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x6fe120, 0xc4200ca730)
	/usr/local/go/src/runtime/panic.go:458 +0x243
main.main.func1(0x8cf560, 0xc4204b2f70, 0xc4203f8b40)
	/home/u/go/src/github.com/7fffffff/unrolledrendertest/main.go:19 +0x3bd
net/http.HandlerFunc.ServeHTTP(0xc42000d2f0, 0x8cf560, 0xc4204b2f70, 0xc4203f8b40)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0x8efe20, 0x8cf560, 0xc4204b2f70, 0xc4203f8b40)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420108380, 0x8cf560, 0xc4204b2f70, 0xc4203f8b40)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4200ba100, 0x8cfba0, 0xc42023e180)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

If only one instance of wrk is running, there are no panics.

I think the root cause is the [call to Render.addLayoutFuncs()](https://github.com/unrolled/render/blob/3b76406bf919236a9661785ab96598302ade10cd/render.go#L334), which modifies a template. It seems possible for a request to call Render.HTML() (and thus addLayoutFuncs()) before a previous request has finished rendering.

Adding a mutex to Render seems to work. But it may also be possible to avoid locking through the use of Template.Clone()

**Comment by unrolled** [comment]
Good find! Can you put together a PR for this?
